// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: evnode/v1/config.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetNamespaceResponse returns the namespace for this network
type GetNamespaceResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HeaderNamespace string                 `protobuf:"bytes,1,opt,name=header_namespace,json=headerNamespace,proto3" json:"header_namespace,omitempty"`
	DataNamespace   string                 `protobuf:"bytes,2,opt,name=data_namespace,json=dataNamespace,proto3" json:"data_namespace,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetNamespaceResponse) Reset() {
	*x = GetNamespaceResponse{}
	mi := &file_evnode_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNamespaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNamespaceResponse) ProtoMessage() {}

func (x *GetNamespaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNamespaceResponse.ProtoReflect.Descriptor instead.
func (*GetNamespaceResponse) Descriptor() ([]byte, []int) {
	return file_evnode_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *GetNamespaceResponse) GetHeaderNamespace() string {
	if x != nil {
		return x.HeaderNamespace
	}
	return ""
}

func (x *GetNamespaceResponse) GetDataNamespace() string {
	if x != nil {
		return x.DataNamespace
	}
	return ""
}

// GetSignerInfoResponse returns information about the signer
type GetSignerInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSignerInfoResponse) Reset() {
	*x = GetSignerInfoResponse{}
	mi := &file_evnode_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignerInfoResponse) ProtoMessage() {}

func (x *GetSignerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evnode_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignerInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSignerInfoResponse) Descriptor() ([]byte, []int) {
	return file_evnode_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *GetSignerInfoResponse) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

var File_evnode_v1_config_proto protoreflect.FileDescriptor

const file_evnode_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x16evnode/v1/config.proto\x12\tevnode.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x16evnode/v1/evnode.proto\x1a\x15evnode/v1/state.proto\"h\n" +
	"\x14GetNamespaceResponse\x12)\n" +
	"\x10header_namespace\x18\x01 \x01(\tR\x0fheaderNamespace\x12%\n" +
	"\x0edata_namespace\x18\x02 \x01(\tR\rdataNamespace\"1\n" +
	"\x15GetSignerInfoResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress2\xa7\x01\n" +
	"\rConfigService\x12I\n" +
	"\fGetNamespace\x12\x16.google.protobuf.Empty\x1a\x1f.evnode.v1.GetNamespaceResponse\"\x00\x12K\n" +
	"\rGetSignerInfo\x12\x16.google.protobuf.Empty\x1a .evnode.v1.GetSignerInfoResponse\"\x00B/Z-github.com/evstack/ev-node/types/pb/evnode/v1b\x06proto3"

var (
	file_evnode_v1_config_proto_rawDescOnce sync.Once
	file_evnode_v1_config_proto_rawDescData []byte
)

func file_evnode_v1_config_proto_rawDescGZIP() []byte {
	file_evnode_v1_config_proto_rawDescOnce.Do(func() {
		file_evnode_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_evnode_v1_config_proto_rawDesc), len(file_evnode_v1_config_proto_rawDesc)))
	})
	return file_evnode_v1_config_proto_rawDescData
}

var file_evnode_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_evnode_v1_config_proto_goTypes = []any{
	(*GetNamespaceResponse)(nil),  // 0: evnode.v1.GetNamespaceResponse
	(*GetSignerInfoResponse)(nil), // 1: evnode.v1.GetSignerInfoResponse
	(*emptypb.Empty)(nil),         // 2: google.protobuf.Empty
}
var file_evnode_v1_config_proto_depIdxs = []int32{
	2, // 0: evnode.v1.ConfigService.GetNamespace:input_type -> google.protobuf.Empty
	2, // 1: evnode.v1.ConfigService.GetSignerInfo:input_type -> google.protobuf.Empty
	0, // 2: evnode.v1.ConfigService.GetNamespace:output_type -> evnode.v1.GetNamespaceResponse
	1, // 3: evnode.v1.ConfigService.GetSignerInfo:output_type -> evnode.v1.GetSignerInfoResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_evnode_v1_config_proto_init() }
func file_evnode_v1_config_proto_init() {
	if File_evnode_v1_config_proto != nil {
		return
	}
	file_evnode_v1_evnode_proto_init()
	file_evnode_v1_state_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_evnode_v1_config_proto_rawDesc), len(file_evnode_v1_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_evnode_v1_config_proto_goTypes,
		DependencyIndexes: file_evnode_v1_config_proto_depIdxs,
		MessageInfos:      file_evnode_v1_config_proto_msgTypes,
	}.Build()
	File_evnode_v1_config_proto = out.File
	file_evnode_v1_config_proto_goTypes = nil
	file_evnode_v1_config_proto_depIdxs = nil
}
